version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres_novit
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: datos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - novit-network

  api:
    image: ghcr.io/maxiid24/academianovit2025-api:latest
    container_name: novit_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=datos;Username=postgres;Password=postgres
    networks:
      - novit-network
    restart: always

volumes:
  pgdata:

networks:
  novit-network:
