name: GH-build-DEV

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar proyecto
        run: dotnet build --no-restore --configuration Release

      - name: Ejecutar tests
        run: dotnet test --no-build --verbosity normal

      - name: Enviar correo con DebugMail
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: |
          sudo apt update
          sudo apt install -y msmtp
          echo "account default
          host $SMTP_HOST
          port 25
          auth on
          user $SMTP_USER
          password $SMTP_PASS
          from test@localhost
          tls off" > ~/.msmtprc
          chmod 600 ~/.msmtprc

          echo -e "Subject: ✅ Pipeline completado\n\nEl workflow GH-build-DEV se ejecutó correctamente." | msmtp maxi@NovitTp2.app.debugmail.io
